spring:
  application:
    name: player-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.206.206:8848  #nacos端口


  main:
    allow-bean-definition-overriding: true



server:
  port: 8083
