server:
  port: 8088

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  application:
    name: news-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.206.206:8848  #nacos端口
        namespace: 953f09b3-9f6f-45e4-8e44-53e6b5c7cc53

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.38.150/football_news
    username: football_News
    password: 183022