server:
  port: 90

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  application:
    name: news-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.206.206:8848  #nacos端口
        ip: 1.15.170.195
        port: 90
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.38.150/football_news
    username: football_News
    password: 183022