server:
  port: 8090

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  application:
    name: news-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.206.206:8848  #nacos端口
        namespace: e2686c2c-46ce-48e7-819f-4b335ebe9dda
  #        ip: 1.15.170.195
#        port: 8090
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.145.176:3306/football_news_db?useSSL=false&serverTimezone=UTC
    username: remoteUser
    password: superremote
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true