spring:
  application:
    name: administrator-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.206.206:8848  #nacos端口
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.170.195:3306/administrator
    username: administrator
    password: 3K36za337n32DcBe

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8085