spring:
  application:
    name: administrator-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.206.206:8848  #nacos端口
        namespace: 4904a6a1-1c1f-435a-b566-f8c71b8fca1e
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.170.195:3306/administrator
    username: administrator
    password: 3K36za337n32DcBe
  main:
    allow-bean-definition-overriding: true

  mail: # 设置发送者邮箱
    host: smtp.qq.com
    username: 2226026498@qq.com
    password: edoxcuedhagsdjff
    default-encoding: UTF-8

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  token:
    signKey: superusers
    expire: 3600000

server:
  port: 8085