spring:
  application:
    name: forum-service  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 110.40.206.206:8848  #nacos端口
        namespace: 4904a6a1-1c1f-435a-b566-f8c71b8fca1e
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.206.206:3306/football-user?useSSL=false&serverTimezone=Asia/Shanghai
    username: football-user
    password: Z7xMRj85tyNAs8SC
  main:
    allow-bean-definition-overriding: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


server:
  port: 8082
